import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StoreProvider  from './StoreProvider'
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><StoreProvider>{children}</StoreProvider></body>
    </html>
  );
}

export default RootLayout