name: Deploy to Sandbox

on: 
  workflow_dispatch:
    inputs:
      service-acct-username:
        description: 'Cloud.gov service account username'
        required: true
        type: string
      service-acct-password:
        description: 'Cloud.gov service account password'
        required: true
        type: string

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cloud Foundry cli
        id: install-cf-cli
        run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v8&source=github" | tar -zx

      - name: Deploy app to sandbox
        id: deploy-to-cloudgov-sandbox
        run: |
          echo $GITHUB_EVENT_PATH
          echo jq '.' $GITHUB_EVENT_PATH
#          SVC_ACCT_PASSWORD=$(jq -r '.inputs.service-acct-password' $GITHUB_EVENT_PATH)
#          echo "::add-mask::${SVC_ACCT_PASSWORD}"
#          echo SVC_ACCT_PASSWORD=$SVC_ACCT_PASSWORD >> $GITHUB_OUTPUT
#          ./cf login -a api.fr.cloud.gov -u ${{ github.event.inputs.service-acct-username }} -p $SVC_ACCT_PASSWORD
#          ./cf push
