name: Deploy
concurrency: production
on: workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build
      - name: Install Cloud Foundry
        run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v8&source=github" | tar -zx
      - name: Cloud Foundry Auth
        env:
          CF_USERNAME: ${{ secrets.CLOUD_GOV_DEPLOY_USERNAME }}
          CF_PASSWORD: ${{ secrets.CLOUD_GOV_DEPLOY_PASSWORD }}
        run: ./cf login -a api.fr.cloud.gov -u ${CF_USERNAME} -p ${CF_PASSWORD}
      - run: ./cf push