name: Deploy to Sandbox

on: 
  workflow_dispatch:
    inputs:
      service-acct-username:
        description: 'Cloud.gov service account username'
        required: true
        type: string
      service-acct-password:
        description: 'Cloud.gov service account password'
        required: true
        type: string

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build code
        id: build-code
        run: |
          npm ci
          npm run build

      - name: Install Cloud Foundry cli
        id: install-cf-cli
        run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v8&source=github" | tar -zx

      - name: Deploy app to sandbox
        id: deploy-to-cloudgov-sandbox
        run: |
          SVC_ACCT_SECRET=${{ github.event.inputs.service-acct-password }}
          echo "::add-mask::${SVC_ACCT_SECRET}}"
          echo SVC_ACCT_SECRET=$SVC_ACCT_SECRET >> $GITHUB_OUTPUT
          ./cf login -a api.fr.cloud.gov -u ${{ github.event.inputs.service-acct-username }} -p $SVC_ACCT_SECRET
          ./cf push
