name: Deploy to Sandbox

on: 
  workflow_dispatch:
    inputs:
      cf-service-acct-username:
        description: 'Cloud.gov service account username'
        required: true
        type: string
      cf-service-acct-password:
        description: 'Cloud.gov service account password'
        required: true
        type: string

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build code 
        run: |
          npm ci
          npm run build

      - name: Install Cloud Foundry
        run: |
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v8&source=github" | tar -zx

      - name: Deploy app to sandbox
        run: |
          ./cf login -a api.fr.cloud.gov -u ${{ github.event.inputs.cf-service-acct-username }} -p ${{ github.event.inputs.cf-service-acct-password }}
          ./cf push