name: Main

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build
      - run: npm run coverage
      - name: Upload Coverage Data
        uses: actions/upload-artifact@v4
        with:
          name: verify-prototype-covearge-${{ github.sha }}.json
          path: coverage/coverage.json
          